#*************************************************************************
# * Copyright (c) 2025 The Eclipse Foundation and others.
# *
# * This program and the accompanying materials are made available under
# * the terms of the Eclipse Public License 2.0 which accompanies this
# * distribution, and is available at https://www.eclipse.org/legal/epl-2.0
# *
# * SPDX-License-Identifier: EPL-2.0
# *************************************************************************/

version = 1
SPDX-PackageName = "Eclipse Dash"
SPDX-PackageSupplier = "Wayne Beaton <wayne.beaton@eclipse-foundation.org>"
SPDX-PackageDownloadLocation = "https://github.com/eclipse-dash/dash-licenses"

[[annotations]]
path = "CODE_OF_CONDUCT.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "DEPENDENCIES"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = ".project"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = ".classpath"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = ".settings/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/.project"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/.classpath"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/.settings/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "maven-plugin/.project"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "maven-plugin/.classpath"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "maven-plugin/.settings/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/test_data_yarn**.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Contributors to the Eclipse Theia Project"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/test_data_package-lock.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Contributors to the Eclipse Vorto Project"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/test_data_package-lock-v2.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Contributors to the Eclipse Ditto Project"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/test_data_package-lock-v3-theia.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Contributors to the Eclipse Theia Project"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/test_data_package-lock-v2-2.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Microsoft Corp."
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "core/src/test/resources/test_data_package-lock-v3.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Contributors to the Eclipse Langium Project"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "core/src/test/resources/test_data_asn1crypto.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Contributors to pypi.org"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "core/src/test/resources/test_data_curation-1.0.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018,2021 Contributors to ClearlyDefined"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "core/src/test/resources/licenses.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/chalk.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Sindre Sorhus"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "core/src/test/resources/definitions.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Contributors to ClearlyDefined"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "core/src/test/resources/lockfile-1.1.0.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Contributors to ClearlyDefined"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "core/src/test/resources/write-1.0.3.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Contributors to ClearlyDefined"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "core/src/test/resources/differentResolved.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Red Hat"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "maven-plugin/src/it/**/pom.xml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Red Hat"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 The Eclipse Foundation"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "core/src/test/resources/fixtures/pnpm/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Simon Reis"
SPDX-License-Identifier = "EPL-2.0"
